sudo: required
language: node_js
node_js:
  - "6.11"
  - "7.10"
  - "node"
branches:
  only:
    - master
env:
  global:
    - CXX=g++-4.8
  matrix:
    - GIT_VERSION=default
    - GIT_VERSION=edge
matrix:
  exclude:
    - node_js: "5.3"
      env: GIT_VERSION=edge
    - node_js: "6.11"
      env: GIT_VERSION=edge
    - node_js: "7.10"
      env: GIT_VERSION=edge
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
before_install:
  - "if [[ `npm -v` == 5* ]]; then npm install -g npm@4.6.1; fi "
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_script:
  - if [[ `npm --version` != 5* ]]; then npm cache clean; fi
  - npm install -g grunt-cli
  - if [ "$GIT_VERSION" = "edge" ]; then sudo add-apt-repository ppa:git-core/ppa -y && sudo apt-get update -q && sudo apt-get install -y git; fi
  - git config --global user.email "test@testy.com"
  - git config --global user.name "Test testy"
  - git version
  - grunt -d
after_script:
  - grunt travisnpmpublish
