sudo: required
language: node_js
node_js:
  - node
  - "12"
  - "10"
branches:
  only:
    - master
env:
  matrix:
    - GIT_VERSION=edge
    - GIT_VERSION=default
matrix:
  exclude:
    - node_js: "12"
      env: GIT_VERSION=edge
    - node_js: "10"
      env: GIT_VERSION=edge
addons:
  apt:
    packages:
      - xvfb
      - libgconf-2-4
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - if [ "$GIT_VERSION" = "edge" ]; then sudo add-apt-repository ppa:git-core/ppa -y && sudo apt-get update -q && sudo apt-get install -y git; fi
  - npm ci
before_script:
  - git config --global user.email "test@testy.com"
  - git config --global user.name "Test testy"
  - git version
  - npm run build
after_success:
  - npm run travisnpmpublish
